### ISSUE TITLE
@Changes should reflect the initial/default value of an Input

### ISSUE THREAD

**Issue by maxime1992** [brechtbilliet/ngxReactiveToolkit#6]
I do have an input like that:

```
  @Input() public target: TARGET = TARGET.SIDENAV;
  @Changes('target') public target$: Observable<TARGET>;
```

But `target$` does not starts with `TARGET.SIDENAV`.

**Comment by RubenVermeulen** [comment]
He @maxime1992, thanks for letting us know. I don't see an easy solution to fix this problem. I think we would have to rewrite a lot for this to work.

The problem is that there isn't a way to access other properties from a component except for the one who has the Changes decorator.

I'll mark this one as an enhancement for the future.

**Comment by RubenVermeulen** [comment]
Target contains several properties. One if them is ngOnChanges. This one we use to next new values to the correct observable. However target does not contain properties from input decorators or any other properties the we can use for that matter.

When you set an initial value for your input property that doesn't trigger ngOnChanges. So we can't use the ngOnChanges for this.

**Comment by maxime1992** [comment]
I see, thanks for explaining.

**Comment by RubenVermeulen** [comment]
Hi @maxime1992 

Since the latest release it's now possible to assign a default value to the @Changes decorator.

`@Changes('INPUT_NAME', 'INITIAL_VALUE')
`
This solution is a path in between but solves your request.
